name: Update JSON on Merge Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Update JSON
      run: |
        python calculate.py  # Replace with the actual filename of your Python script

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update JSON file"
        git push
