name: Run calculate.py on PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  calculate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run calculate.py
      run: python calculate.py


      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
